import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/system";
import Navbar from "./components/Navbar";

const leagueSpartan = League_Spartan({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${leagueSpartan.className} relative bg-white`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
